program name:day.x

program DAYPRG{
version DAYVER{
string day(void)=1;
}=1;
}=0x20000001;
// compiling day.x using rpcgen
$ rpcgen –a day.x
$ ls 
// seeing the list of files which gets created(6 files)
$ day.h day.x day_client.c day_clnt.c day_server.c day_svc.c Makefile.day
// open day_server.c to do changes.
//day_server.c
/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "day.h"
#include "time.h"

char **
day_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
    time_t t;
    time(&t);
    result=ctime(&t);  //&t returns time and ctime gives the correct format of time 

	return &result;
}
// open day_client.c to make changes
//day_client.c
/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "day.h"


void
dayprg_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char *day_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DAYPRG, DAYVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = day_1((void*)&day_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
printf("%s",*result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}
int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	dayprg_1 (host);
exit (0);
} 
OUTPUT: 
//compiling server and server stub program
$ cc day_server.c day_svc.c –o rday
$ ./rday		(In Server Terminal)

 
$ cc day_client.c day_clnt.c
$ ./a.out 10.2.0.3	(In Client Terminal)
